const OK = 200
const CREATED = 201
const BAD_REQUEST = 400
const UNAUTHORIZED = 401
const WS_CURR_PLAYER=1
const WS_CARD_LIST=2
const WS_SUSPICION=4
const WS_PICK_CARD=8
const WS_SUSPICION_STATUS=16
const WS_SENT_CARD_NOTIFY=32
const WS_AVAIL_MOVES=64
const WS_POS_LIST=128
const WS_ROOM=256
const WS_ACCUSATION=512
const WS_LOST=1024
const WS_SALEM=2048
const WS_CHAT_MSG=8192


export {OK, CREATED, BAD_REQUEST, UNAUTHORIZED, WS_CURR_PLAYER, WS_CARD_LIST, WS_SUSPICION, 
        WS_PICK_CARD, WS_SUSPICION_STATUS, WS_SENT_CARD_NOTIFY, WS_AVAIL_MOVES, 
        WS_POS_LIST, WS_ROOM, WS_ACCUSATION, WS_LOST, WS_SALEM, WS_CHAT_MSG}